apiVersion: v1
kind: Service
metadata:
  name: secure-shop-service
  namespace: secureapp
  labels:
    app: secure-shop
spec:
  type: LoadBalancer
  selector:
    app: secure-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
